# Generated by Django 5.2 on 2025-08-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModule', '0002_alter_users_loginat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('SellerID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreAddress', models.CharField(max_length=255)),
                ('ProductionLicenseNumber', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=50, unique=True)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='UserModule.users')),
            ],
        ),
    ]
