# Generated by Django 5.2 on 2025-08-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0001_initial'),
        ('UserModule', '0002_alter_users_loginat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='StoreName',
            field=models.CharField(default='My Store', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_requests', to='UserModule.users'),
        ),
    ]
