# Generated by Django 5.2 on 2025-08-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0002_seller_storename_alter_seller_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(blank=True, max_length=150, null=True)),
                ('ProductName', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
                ('SubCategories', models.JSONField(blank=True, default=list)),
                ('Units', models.JSONField(blank=True, default=list)),
                ('Stock', models.IntegerField(default=0)),
                ('Specifications', models.JSONField(blank=True, default=list)),
                ('Images', models.JSONField(blank=True, default=list)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SellerModule.seller')),
            ],
        ),
    ]
