# Generated by Django 5.2 on 2025-08-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0005_category_image_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Status',
            new_name='status',
        ),
    ]
