# Generated by Django 5.2 on 2025-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0006_rename_categoryid_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
