# Generated by Django 5.2 on 2025-11-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0007_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='SellerModule.category')),
            ],
        ),
    ]
