# Generated by Django 5.2 on 2025-11-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0008_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Category',
            new_name='CategoryID',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('CategoryID', 'Name')},
        ),
    ]
