# Generated by Django 5.2 on 2026-07-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0010_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
