# Generated by Django 5.2 on 2025-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('basic', 'Basic User'), ('seller', 'Seller'), ('admin', 'Admin')], default='basic', max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LoginAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
