# Generated by Django 5.2 on 2025-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='LoginAt',
            field=models.DateTimeField(),
        ),
    ]
