# Generated by Django 5.2 on 2026-07-07 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0011_alter_category_image'),
        ('UserModule', '0002_alter_users_loginat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='UserModule.users')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Products', models.JSONField(default=list)),
                ('TotalAmount', models.FloatField(default=0)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('PaymentMethod', models.CharField(default='Cash', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='SellerModule.seller')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='UserModule.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('SelectedUnit', models.JSONField()),
                ('UnitType', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=1)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('AddedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='SellerModule.product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='UserModule.users')),
            ],
            options={
                'unique_together': {('UserID', 'ProductID', 'UnitType', 'Status')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('AnalyticsID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalSales', models.PositiveIntegerField(default=0)),
                ('SalesLast30Days', models.PositiveIntegerField(default=0)),
                ('AvgSalesPerDay', models.FloatField(default=0)),
                ('Revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LastSaleDate', models.DateField(blank=True, null=True)),
                ('DaysSinceLastSale', models.PositiveIntegerField(default=0)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='SellerModule.product')),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='SellerModule.seller')),
            ],
            options={
                'unique_together': {('ProductID', 'SellerID')},
            },
        ),
    ]
