# Generated by Django 5.2 on 2025-11-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0007_product_description'),
        ('UserModule', '0002_alter_users_loginat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('SelectedUnit', models.JSONField()),
                ('UnitType', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=1)),
                ('ViewCount', models.IntegerField(default=0)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('AddedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='SellerModule.product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='UserModule.users')),
            ],
            options={
                'unique_together': {('UserID', 'ProductID', 'UnitType', 'Status')},
            },
        ),
    ]
