# Generated by Django 5.2 on 2026-07-07 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0003_feedback_transaction_cart_productanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
