# Generated by Django 5.2 on 2025-11-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0009_rename_category_tag_categoryid_and_more'),
        ('UserModule', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ViewCount',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Products', models.JSONField(default=list)),
                ('TotalAmount', models.FloatField(default=0)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('PaymentMethod', models.CharField(default='Cash', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='SellerModule.seller')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='UserModule.users')),
            ],
        ),
    ]
