# Generated by Django 5.2 on 2026-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0004_alter_transaction_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalytics',
            name='SalesGrowthRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productanalytics',
            name='SalesLast7Days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productanalytics',
            name='SalesPrevious7Days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
