# Generated by Django 5.2 on 2026-06-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerModule', '0009_rename_category_tag_categoryid_and_more'),
        ('UserModule', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('AnalyticsID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalSales', models.PositiveIntegerField(default=0)),
                ('SalesLast30Days', models.PositiveIntegerField(default=0)),
                ('AvgSalesPerDay', models.FloatField(default=0)),
                ('Revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LastSaleDate', models.DateField(blank=True, null=True)),
                ('DaysSinceLastSale', models.PositiveIntegerField(default=0)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='SellerModule.product')),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='SellerModule.seller')),
            ],
            options={
                'unique_together': {('ProductID', 'SellerID')},
            },
        ),
    ]
