"""Django settings for VendorProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import sys  # Add this import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ========== ADD PYTHON PATH FOR UTILS ==========
# Add utils folder to Python path (utils is inside VendorProject)
UTILS_PATH = BASE_DIR / 'utils'  # Change this line

# Check if utils directory exists and add to Python path
if UTILS_PATH.exists():
    sys.path.insert(0, str(UTILS_PATH))
    print(f"✓ Added utils to Python path: {UTILS_PATH}")  # Optional debug
else:
    print(f"✗ Utils not found at: {UTILS_PATH}")  # Optional debug
# ===============================================


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@z%!7az)41u--$y*&@0f2mz)5p&8+1@+(#2i9o_#t6$^rk@w#^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'UserModule',
    'SellerModule',
    'superadmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'VendorProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # your global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #Seller User Info section
                'SellerModule.context_processors.seller_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'VendorProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   
        'NAME': 'vendor',
        'USER': 'root',
        'PASSWORD': 'hom123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#extra import section



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Tell Django where to look for additional static files (besides app static folders)
STATICFILES_DIRS = [
    BASE_DIR / "static",   # your project-level static folder
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Expire session after 24 hours
SESSION_COOKIE_AGE = 24 * 60 * 60  # 24 hours in seconds

# Optional: set to True if you want session to end when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Media folder configuration
MEDIA_URL = '/media/'  # URL to access media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Physical folder in project
MEDIA_ROOT = BASE_DIR / "media"